<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Berries.png" />
    <None Remove="Images\Branches.png" />
    <None Remove="Images\BukQ.png" />
    <None Remove="Images\Carol.png" />
    <None Remove="Images\Eggs.png" />
    <None Remove="Images\Feather.png" />
    <None Remove="Images\FeatherCompass.png" />
    <None Remove="Images\Glass.png" />
    <None Remove="Images\John.png" />
    <None Remove="Images\Kosi.png" />
    <None Remove="Images\LesQ.png" />
    <None Remove="Images\Log.png" />
    <None Remove="Images\Menu.png" />
    <None Remove="Images\MestoQ.png" />
    <None Remove="Images\Moss.png" />
    <None Remove="Images\Nest.png" />
    <None Remove="Images\NestE.png" />
    <None Remove="Images\Noir.png" />
    <None Remove="Images\Owl.png" />
    <None Remove="Images\ParkQ.png" />
    <None Remove="Images\PotokQ.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Berries.png" />
    <Resource Include="Images\Branches.png" />
    <Resource Include="Images\BukQ.png" />
    <Resource Include="Images\Carol.png" />
    <Resource Include="Images\Eggs.png" />
    <Resource Include="Images\Feather.png" />
    <Resource Include="Images\FeatherCompass.png" />
    <Resource Include="Images\Glass.png" />
    <Resource Include="Images\John.png" />
    <Resource Include="Images\Kosi.png" />
    <Resource Include="Images\LesQ.png" />
    <Resource Include="Images\Log.png" />
    <Resource Include="Images\Menu.png" />
    <Resource Include="Images\MestoQ.png" />
    <Resource Include="Images\Moss.png" />
    <Resource Include="Images\Nest.png" />
    <Resource Include="Images\NestE.png" />
    <Resource Include="Images\Noir.png" />
    <Resource Include="Images\Owl.png" />
    <Resource Include="Images\ParkQ.png" />
    <Resource Include="Images\PotokQ.png" />
  </ItemGroup>

</Project>
